### ISSUE TITLE
peer to peer morning session Kehinde, Ghislain, Promisse, anas 30th 8 2022

### ISSUE THREAD

**Issue by GhislainMitahi** [kendoriddy/Leaderboard#9]
### Good work so far!

:heavy_check_mark: code readable, and 
:heavy_check_mark: Github flow implemented, 
:heavy_check_mark: The good module usage.
 :heavy_check_mark: No linter issues, 
:heavy_check_mark:  Developed in professional way.

**Comment by kendoriddy** [comment]
Thank you
